# Generated by Django 4.2.7 on 2023-11-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_remove_user_nickname_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
    ]
