# Generated by Django 4.2.7 on 2023-11-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_table_options_reservedtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedtable',
            options={'verbose_name': 'Бронированный стол', 'verbose_name_plural': 'Бронированные столы'},
        ),
    ]
