# Generated by Django 4.2.7 on 2023-11-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_reservedtable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('just', 'Обычный'), ('vip', 'VIP'), ('booths', 'Кабинки')], max_length=20, verbose_name='Тип'),
        ),
    ]
