# Generated by Django 4.2.7 on 2023-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtable',
            name='data',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
