# Generated by Django 4.2.7 on 2023-11-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_reservedtable_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
    ]
