# Generated by Django 4.2.7 on 2023-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_type_of_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
    ]
