# Generated by Django 4.2.7 on 2023-12-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketfood',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.basketmodel', verbose_name='Корзинка'),
        ),
    ]
