# Generated by Django 4.2.7 on 2023-12-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('basket', '0003_alter_basketfood_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food', verbose_name='Еда'),
        ),
    ]
